[package]
name = "soroban-flash-loan-receiver-standard"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = "0.3.2"
soroban-auth = "0.3.2"

[dev_dependencies]
soroban-sdk = { version = "0.3.2" }
soroban-auth = { version = "0.3.2" }